### ISSUE TITLE
Re-Editing the levels

### ISSUE THREAD

**Issue by shoc71** [shoc71/Keep-On-Going#217]
certain levels feel shallow or completely cut in half. Not intentional during the inception of the creation for this game, however, levels require complete re-works where...

The top half is difficult based on timing jumps while the bottom half takes more effort to get to the solution (both are solvable). The Sonic The Hedgehog solution to the problem of needing to use multiple stages of the levels and managing to both challenge and allow new players to solve the level eventually.

Using whole levels is rather difficult unless the route is not planned for ahead of time.

Note - this idea only came after torches (3rd/august/2023)

**Comment by shoc71** [comment]
I like the labels keep them up

**Comment by slysnivy** [comment]
@shoc71 I managed to play some levels and had a volunteer play tester try the levels. We made it to level 13 and here are the current results:
- Put more easier levels at the start (even if it's a repeat idea, like the hit space or level 3). This will give players more time to get used to the physics/jumping. We should put a simple level before hallways and introduce elements that way (self.platforms and self.win_zones in one, self.death_zone in another, self.respawn, and then introduce self.draw with it's rules where it's any color except for the ones described before). The levels after will be a good review since they'll be more detailed).
- Candles is a bit too difficult (for it's position/level number in the main set). Also this level needs a redesign, as the play tester thought the dripping wax were walls (maybe we do dynamic stuff?) or keep it simple. Another issue with this level is that the last candle has no collision for some reason.
- Letters is way too hard. I think we should avoid the use of the elevator step ups (we could do the teleporter idea). It could also use some color, like this: 
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/7e2cab54-d46a-41dc-ac1a-eb096702b48f).

Overall, we should **focus on more** visually appealing levels and **put less focus** on the level mechanics (and how we can make it different)

**Comment by shoc71** [comment]
I agree with a lot of what is being said here, however, there are a lot of levels later that need to be introduced beforehand like avoid_red and split_path and signals. I made a lot of these levels with ease in mind and just made letters way too soon. I'll put a patch for that soon, however, I think what we should do is lock some of the levels so that players are not allowed to access it unless they have beaten the main branch.

**Comment by slysnivy** [comment]
@shoc71 Should we close this issue since it's no longer relevant and open up another one more relevant to our direction?

**Comment by shoc71** [comment]
yes, agreed. Close this whenever you'd like
