### ISSUE TITLE
Reviewing levels

### ISSUE THREAD

**Issue by shoc71** [shoc71/Keep-On-Going#382]
- some levels in the game are downright impossible to beat or extremely time-consuming (in the hard setting speed), all the other levels are possible to beat on the medium setting. (easy not tested yet)
- List includes but is not limited to ["Red Boss Volcano", "Into the cave", "Lamp Post"] # found in txt_lvls 4,6,6 respectively

and more... 

This needs to be patched and fixed. This issue can only be resolved once the levels are officially categorized correctly based on their difficulty or we remove it from the main timeline of the story.

**Comment by slysnivy** [comment]
@shoc71 I believe we should first try to craft a narrative in our story and base our levels on that. In that way, we can have a clearer vision on what levels we want and how they can be designed.

**Comment by shoc71** [comment]
> @shoc71 I believe we should first try to craft a narrative in our story and base our levels on that. In that way, we can have a clearer vision on what levels we want and how they can be designed.

I have been following a sort of theme or mini-stories for each of the hub. Some hubs may have more than one mini-story in them depending on the amount of time, I have on a given day. They are listed as the following (subject to change). Some levels exist as standalone. 

hub1
- 001-tut
- 003 story

- going through the woods
- smooth tutorial like playthrough (getting the player use to the jumping mechanism and precision)

hub2
- 002 half-screen
- climbing out of the city

hub3
- 004 70lava

hub4
- 005 autocomplete

hub5
- 006 sacrifice

hub6
- 007 block maze

hub7
- 008 respawn

hub8
- 009 blue

**Comment by slysnivy** [comment]
Yea, that's good, I'll check out the mini stories soon

**Comment by shoc71** [comment]
Ngl, they are not in order yet... Here's the update on the [excel](https://docs.google.com/spreadsheets/d/1k4hGtyzFeRAulf-8Fta5CI69PNqdWIoKs4LxAmOilHs/edit#gid=0)

**Comment by slysnivy** [comment]
This is related to #303 as well

**Comment by slysnivy** [comment]
@shoc71 Taking into account your current beta testers, I think it's less of a problem of level design and more of keeping track of the player. There might not even be a problem at all.

Let's take Geometry Dash as an example since it shares similar controls, speeds, and difficulty. One thing to consider is that in Geometry Dash, that player is larger than our 10x10 player, which means you could see it better. Another consideration is that difficulty isn't a problem in the first place, as in Geometry Dash, it's normal to have attempts go in the 100's. Furthermore, since you mentioned that you beat all the levels within 1 hour suggests that there is definitely a skill curve for players to progress. 

Therefore, I think the difficulty is something good and shouldn't be adjusted due to the limited exposure of the beta testers (I'm guessing a few tries or 10 minutes, correct me if I'm wrong). If we want to, we can make minor adjustments and improvements to help the player, but I don't think it requires an entire overhaul.

**Comment by shoc71** [comment]
> @shoc71 Taking into account your current beta testers, I think it's less of a problem of level design and more of keeping track of the player. There might not even be a problem at all.
> 
> Let's take Geometry Dash as an example since it shares similar controls, speeds, and difficulty. One thing to consider is that in Geometry Dash, that player is larger than our 10x10 player, which means you could see it better. Another consideration is that difficulty isn't a problem in the first place, as in Geometry Dash, it's normal to have attempts go in the 100's. Furthermore, since you mentioned that you beat all the levels within 1 hour suggests that there is definitely a skill curve for players to progress.
> 
> Therefore, I think the difficulty is something good and shouldn't be adjusted due to the limited exposure of the beta testers (I'm guessing a few tries or 10 minutes, correct me if I'm wrong). If we want to, we can make minor adjustments and improvements to help the player, but I don't think it requires an entire overhaul.

Thanks for your input on this and after some thought and a read-through of this, I think you might be right.

**Comment by shoc71** [comment]
@slysnivy https://docs.google.com/spreadsheets/d/1k4hGtyzFeRAulf-8Fta5CI69PNqdWIoKs4LxAmOilHs/edit#gid=1069114784

Whenever you get the time go through this list and input your thoughts about each level. (anytime after dec/1/2023)

**Comment by shoc71** [comment]
To elaborate more on this idea... I'm going to rank the levels in order of difficult for their own hubzones (closer you are to the end, the harder the levels are going to be)

**Comment by slysnivy** [comment]
@shoc71 Ok, so far I played the first 74 levels which includes completing hub 1 and 2 entirely. The individual levels are ok, but the entire hub 1 and 2 as a whole need to be reworked, as I wouldn't consider this initial look fit for gameplay. This is arguably the most important part of our game since it's the first set of levels the player looks through and is when they're most likely to drop the game.

I know you mentioned the levels aren't in order which is fine. More importantly, it doesn't have much of an overarching story since you're being thrown in many settings one after another. I believe this is an issue of choosing a set of themes and sticking with it because in these hubs there are too many different themes that conflict with each other. Let's take hub3 or the lava zone, it has the common theme of having a bunch of red, which works despite having slightly different art themes. In the case of hub1/2, there's too many themes that conflict with each other and ruined the experience.

**Comment by slysnivy** [comment]
To solve this problem, I think we can split hub1 and hub2 into more hubs of their own themes (block/plain, tv, houses etc)

**Comment by slysnivy** [comment]
In terms of level design, I think it helps to include a small section from another level to help with world building

**Comment by slysnivy** [comment]
I have just finished my play through of the entire game. I believe I clocked in at 3 hours and 30 minutes on hard (including time taken to write in the excel and not consecutively). 

Overall, less than 50% of the levels cleared both the "pass" and "art" checks, meaning we have a lot of work to do. My thoughts as a whole are that there are a ton of things we need to work on because I kept having frequent thoughts of "I want to play another game", which if I were a real player, I would had done.
