### ISSUE TITLE
Sudden pauses in the game...

### ISSUE THREAD

**Issue by shoc71** [shoc71/Keep-On-Going#443]
- when playing the game usually from time to time I would notice massive spikes in frame rate as the player would stop in mid-air but the music would keep playing as if nothing ever happened.

Here's a video I tried to capture to show this point...

https://github.com/shoc71/Keep-On-Going/assets/129419169/6d14fc06-6055-41c3-bace-045e366125c0

**Comment by slysnivy** [comment]
@shoc71 Did you have google chrome and discord running at the same time? This seems like a memory issue since the music kept playing while the game was calculating stuff.

**Comment by slysnivy** [comment]
This is the closest I can get to the issue described. As I don't have access to your device and couldn't authentically recreate it in my 4 hours of total gameplay (3 hours 30 minutes + 30 minutes debugging for this issue) across two devices (laptop and a mid-end pc), I will close this issue because it seems like a memory issue of your device. 

https://github.com/shoc71/Keep-On-Going/assets/47337807/00498941-03e0-435d-a754-3b1ba37fc883

However, I will make changes in the future to load levels on a per hub basis to ease memory use on our game. Currently, our game uses 1 MB to hold levels, and I hope that reducing this will help with performance. Another thing I could change is the trailing afterimages behind the player and make dust particles instead that don't use transparency in case that's the issue.

**Comment by slysnivy** [comment]
One fix I can think of right now is to 

> * when playing the game usually from time to time I would notice massive spikes in frame rate as the player would stop in mid-air but the music would keep playing as if nothing ever happened.
> 
> Here's a video I tried to capture to show this point...
> 
>  IMG_4402.mov

By the way, the music did pause as well
